
name: Pikabot Autofixes ðŸš¶ðŸ”¥
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "await pika_cmds(event)"
          replace: "bot.pika_cmd"
      - name: Create Pull Request
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Plugins Auto fixes ðŸš¶'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: ItzSjDude
          commit_user_email: Support@itzsjdude.in
          commit_author: ItzSjDude <Support@itzsjdude.in>
